const ADD_CHARACTER = 'ADD_CHARACTER';
const REMOVE_CHARACTER = 'REMOVE_CHARACTER';
const ADD_FAVORITE = 'ADD_FAVORITE';
const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
const FILTER = 'FILTER';
const ORDER = 'ORDER';

export {ADD_CHARACTER,REMOVE_CHARACTER,ADD_FAVORITE,REMOVE_FAVORITE,FILTER,ORDER};  